# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/nicklockwood/SwiftFormat.git
    rev: 0.44.12
    hooks:
    -   id: swiftformat
