name: Swift

on:
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/swift.yaml"
      - "**.swift"
      - "**/Package.resolved"
  pull_request:
    paths:
      - ".github/workflows/swift.yaml"
      - "**.swift"
      - "**/Package.resolved"

jobs:
  swiftformat:
    name: Check swiftformat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: swift build
        run: |
          if [ -d ".build" ]; then
            if ! [ -x "$(command -v swift-format)" ]; then
              sudo cp -f .build/release/swift-format /usr/local/bin/swift-format
            fi
          else
            git clone -b swift-5.2-branch https://github.com/apple/swift-format.git
            cd swift-format
            swift build --disable-sandbox -c release
            mv .build .. && cd ..
            sudo cp -f .build/release/swift-format /usr/local/bin/swift-format
          fi

      - name: Format Swift code
        run: swiftformat --verbose .

      - name: Verify formatted code is unchanged
        run: git diff --exit-code HEAD
